name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: docker/login-action@v3.1.0
      name: Docker Login
      with:
        username: sathurjan
        password: ${{ secrets.DOCKERPW }}

    - uses: docker/build-push-action@v5
      name: Docker Build and Push
      with:
        context: ./app
        tags: sathurjan/devops-ass:latest
        push: true
