name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install bandit

    - name: Run unit tests
      run: |
        cd app
        pytest

    - name: Run Bandit (code scan)
      run: |
        bandit -r app -ll


    - uses: docker/login-action@v3.1.0
      name: Docker Login
      with:
        username: sathurjan
        password: ${{ secrets.DOCKERPW }}

    - uses: docker/build-push-action@v5
      name: Docker Build and Push
      with:
        context: ./app
        tags: sathurjan/devops-ass:latest
        push: true

    - name: Run Trivy image scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: sathurjan/devops-ass:latest
        severity: CRITICAL,HIGH
        exit-code: 1