name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt
        pip install bandit

    - name: Run unit tests
      run: |
        cd app
        pytest

    - name: Run Bandit (code scan)
      run: |
        bandit -r app -ll

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - uses: docker/login-action@v3.1.0
      name: Docker Login
      with:
        username: sathurjan
        password: ${{ secrets.DOCKERPW }}

    - uses: docker/build-push-action@v5
      name: Docker Build
      with:
        context: ./app
        tags: sathurjan/devops-ass:${{ github.sha }}
        load: true

    - name: Run Trivy image scan
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: sathurjan/devops-ass:${{ github.sha }}
        severity: CRITICAL,HIGH
        exit-code: 0

    - uses: docker/build-push-action@v5
      name: Docker Push
      with:
        context: ./app
        tags: sathurjan/devops-ass:${{ github.sha }}
        push: true

    # - name: Build Docker image
    #   run: |
    #     docker build -t devops-challenge:${{ github.sha }} app

    # - name: Login to GHCR
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    # - name: Push Docker image
    #   run: |
    #     IMAGE=ghcr.io/${{ github.repository }}/devops-challenge:${{ github.sha }}
    #     docker tag devops-challenge:${{ github.sha }} $IMAGE
    #     docker push $IMAGE
